# -*- coding: utf-8 -*-
"""char_word_sent_tokenization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCSwRb5lSBnQRUKf1Kv7Yu8Run7tTW0A

**TOKENIZATION**                                                     
Tokenization is the process of converting raw text into smaller meaningful units called tokens.
"""

text = "python"
tokens = list(text)
print(tokens)

"""this is character tokenization"""

text = "I am yash patil"
tokens = text.split()
print(tokens)

"""this is word tokenization"""

text = "I'm, Yash"
tokens = text.split()
print(tokens)

"""this is the issue with split func and word tk

Here comes Libraries to solve this problem

NLTK Tokenizer
"""

!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

from nltk.tokenize import word_tokenize
text = "I'm Yash."
tokens = word_tokenize(text)
print(tokens)

!pip install spacy
!python -m spacy download en_core_web_sm

import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("I'm Yash Patil.")
tokens = [token.text for token in doc]
print(tokens)

"""this was NLTK and SPACY libraries for word tokenization

Sentence Tokenization
"""

text = "I'm yash Patil. I am Happy."
token = text.split('.')
print(token)

"""split() comes with lots of problems"""

text = "I'm yash Patil. I am Happy."
from nltk import sent_tokenize
token = sent_tokenize(text)
print(token)

"""using nltk"""

nlp = spacy.load("en_core_web_sm")
doc = nlp("I'm yash Patil. I am Happy.")
for sent in doc.sents:
  print(sent)

"""using spacy"""

