# -*- coding: utf-8 -*-
"""Hugging Face Tokenization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u4p1B7UNsdQJE-GYNcxiYkkF6w3yWLq1
"""

!pip install transformers

!pip install transformers sentencepiece

from transformers import AutoTokenizer

"""BERT"""

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text = "Hey Google, I'm Yash Patil"
tokens = tokenizer.tokenize(text)
print(tokens)

"""BERT uses WordPiece"""

bert = AutoTokenizer.from_pretrained("bert-base-uncased")

gpt2 = AutoTokenizer.from_pretrained("gpt2")

roberta = AutoTokenizer.from_pretrained("roberta-base")

text = "ChatGPT is amazing!"

print(bert.tokenize(text))
print(gpt2.tokenize(text))
print(roberta.tokenize(text))

"""When you switch models:

BERT → WordPiece
GPT-2 → Byte-Level BPE
RoBERTa → Byte-Level BPE
T5 → SentencePiece
Llama → SentencePiece
"""

text = "I love Python"

tokens = tokenizer.tokenize(text)

print(tokens)

ids = tokenizer.convert_tokens_to_ids(tokens)

print(ids)

tokens = tokenizer.convert_ids_to_tokens(ids)
print(tokens)

"""The encode() Shortcut

Instead of tokenizing and converting IDs separately:
"""

ids = tokenizer.encode(text)

print(ids)

"""The Deocode() Shortcut"""

decoded = tokenizer.decode(ids)

print(decoded)

"""Sentence
"I love Python"

        │
        ▼

tokenize()

['i', 'love', 'python']

        │
        ▼

convert_tokens_to_ids()

[1045, 2293, 18750]

        │
        ▼

Transformer Model

        │
        ▼

Prediction
"""

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
text = "Machine Learning is fun."
tokens = tokenizer.tokenize(text)

print(tokens)

ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

tokens = tokenizer.convert_ids_to_tokens(ids)
print(tokens)