# -*- coding: utf-8 -*-
"""Python NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6MZ99mKEiQBs4Xw41f4NqQy0A1UT2Me

**TEXT PREPROCESSING & CLEANING**

lower casing
"""

text = "I am Yash"

clean = text.lower()
print(clean)

"""Punctations remove"""

import string
text1 = "Heyy!!! How are youuu ??"
clean1 = text1.translate(str.maketrans("","",string.punctuation))
print(clean1)

import re
text2 = "Visit https://www.google.com"
clean2 = re.sub(r"http\S+", "", text2)
print(clean2)

print(string.punctuation)

text3 = "hello!!! yash @"
translator = str.maketrans("","",string.punctuation)
clean3 = text3.translate(translator)
print(clean3)

text4 = "I have 2 balls"
clean4 = re.sub(r'\d+\s',"",text4)
print(clean4)

text_5 = "Hey Yash !!! I am 10 years old, visit https://www.google.com !"

text_5 = text_5.lower()
text_5

text_5 = re.sub(r"https\S+\d+\s","",text_5)
text_5

test_new = re.sub(r"https\S+","",text_5)
test_new

test_new2 = re.sub(r"\d+\S","",test_new)
test_new2

from bs4 import BeautifulSoup

text = "<h1>Hello</h1><p>Welcome</p>"

clean =  BeautifulSoup(text,"html.parser").get_text()
print(clean)

text = "I love pizza 🍕😍"
emoji_pattern = re.compile(
    "["
    "\U0001F600-\U0001F64F"
    "\U0001F300-\U0001F5FF"
    "\U0001F680-\U0001F6FF"
    "\U0001F1E0-\U0001F1FF"
    "]+",
    flags=re.UNICODE,
)

clean = emoji_pattern.sub("",text)
print(clean)

space = " I    am      YASH "
clean = " ".join(space.split())
clean = clean.lower()
print(clean)

import re
import string
from bs4 import BeautifulSoup

def clean_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove HTML tags
    text = BeautifulSoup(text, "html.parser").get_text()

    # Remove URLs
    text = re.sub(r'http\S+', '', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove extra spaces
    text = " ".join(text.split())

    return text


sample = "I LOVE Python!!! Visit https://python.org <b>NOW</b>. Price = 999"

print(clean_text(sample))

import re
from bs4 import BeautifulSoup
import string

def clean_text(text):
  text = text.lower()
  text = BeautifulSoup(text,"html.parser").get_text()
  text = re.sub(r'https\s+',"",text)
  text = text.translate(str.maketrans("","",string.punctuation))
  text = re.sub(r'\d+',"",text)
  text = " ".join(text.split())
  return text

sample = "I LOVE Python!!! Visit https://python.org <b>NOW</b>. Price = 999"

print(clean_text(sample))

reviews = [
    "I LOVE this phone!!! 😍😍",
    "Worst Product Ever!!!!",
    "Amazing Camera....",
    "Battery Life is GREAT!!!!"
]

"""Your Task
Convert to lowercase
Remove punctuation
Remove emojis
Remove extra spaces
"""

emoji_pattern = re.compile(
    "["
    "\U0001F600-\U0001F64F"
    "\U0001F300-\U0001F5FF"
    "\U0001F680-\U0001F6FF"
    "\U0001F1E0-\U0001F1FF"
    "]+",
    flags=re.UNICODE,
)

def reveiw_clean(text):
  for text in text:
    text.lower()



  # text = text.translate(str.maketrans("","",string.punctuation))
  # text = "".join(text.split())
  # text = emoji_pattern.sub("",text)
  return text

print(reveiw_clean(reviews))

reviews = [
    "I LOVE this phone!!! 😍😍",
    "Worst Product Ever!!!!",
    "Amazing Camera....",
    "Battery Life is GREAT!!!!"
]
cleaned_review = []



for review in reviews:
  cleaned_review.append((review.lower()))

print(cleaned_review)

reviews = [
    "I LOVE this phone!!! 😍😍",
    "Worst Product Ever!!!!",
    "Amazing Camera....",
    "Battery Life is GREAT!!!!",
    "Visit https://amazon.in",
    "<h1>Best Mobile</h1>",
    "Price = ₹59,999"
]

import re
import string
from bs4 import BeautifulSoup
clean_review = []
for text in reviews:
    text = text.lower()
    text = BeautifulSoup(text,"html.parser").get_text()
    text = text.translate(str.maketrans("","",string.punctuation))
    text = re.sub(r'https\S+',"",text)
    text = re.sub(r"\d+","",text)
    # text = "".join(text.split())
    clean_review.append(text)
print(clean_review)